= Kotlin Introduction
2017-11
:revnumber: {project-version}
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../java]


== A Short History of Me on the JVM
* Programming Java since 1996 (JDK 1.0)
* Groovy and Grails
* Scala / Spark
* Kotlin over the past year

== Short History of Kotlin
* *2010* - Created
* *2016* - 1.0 Release
* *2017* - 1.1 Release, Android 1^st^ class support


== Basics


=== What is Kotlin
* Statically typed language
* Inspired by Java, Scala, C#, Groovy ...
* Targets
** JVM / Android
** JavaScript
** Native via LLVM

=== Design Goals
* Expressiveness
* 100% Java interoperability
* Excellent tool support

=== Syntax
* Java / C style (no semicolons)
* Inferred types

=== Differences from Java
* ``public`` visibility by default
* Classes ``final`` by default
* No checked Exceptions
* Immutability
* Null safety

=== Demo
* Scripts
* Class-less functions
* Declarations
* Type-inference and Nullable types
* Classes and Objects

== New Abilities
* Extension functions / properties
* Named and default arguments
* ``if`` expressions
* Strings

=== Demo

=== Libraries
* Tornado
* Gradle script Kotlin

== Kotlin vs. Java

Some common code patterns in Java, reimplemented in Kotlin

=== DTO / Value Objects

* A Simple class with one mutable and one immutable property

=== Java
[source,java]
-----
public class Author {
    private final String name;
    private String pseudonym;
    public Author(String name, String pseudonym) { /*...*/ }

    public String getName() { /*...*/ }
    public String getPseudonym() { /*...*/ }
    public void setPseudonym(String pseudonym) { /*...*/ }

    @Override public boolean equals(Object o) { /*...*/ }
    @Override public int hashCode() { /*...*/ }
    @Override public String toString() { /*...*/ }
}
-----

[NOTE.speaker]
--
The real class is around 50 lines long
--

=== Kotlin
[source,java]
-----
data class Author(val name: String, var pseudonym: String)
-----
[NOTE.speaker]
--
The works as a JavaBean with frameworks like Jaxon, Hibernate etc.
--

=== Builder Pattern

Construct an instance of a class in different ways,
often through a fluent API.

[plantuml]
-----
@startuml
class ColourScheme *-- Car
class Propulsion *-- Car
class upholstery *-- Car
class Car {
  -colourScheme: ColourScheme
  -propulsion: Propulsion
  -upholstery: Upholstery
}
@enduml
-----


=== Java (use)
[source,java]
-----
Car defaultCar = new Car.Builder().createCar();

Car nonVeganCar = new Car.Builder()
        .withUpholstery(new Upholstery("leather"))
        .createCar();

Car customCar = new Car.Builder()
        .withColourScheme(new ColourScheme(Color.BISQUE))
        .withPropulsion(new Propulsion("diesel"))
        .withUpholstery(new Upholstery("Gold Stitched Denim"))
        .createCar();
-----

=== Kotlin (use)
[source,java]
-----
val defaultCar = Car()

val nonVeganCar = Car(upholstery = Upholstery("leather"))

val customCar = Car(
        colourScheme = ColourScheme(Color.BISQUE),
        propulsion = Propulsion("diesel"),
        upholstery = Upholstery("Gold Stitched Denim")
    )

// Copy and customise
val betterCustomCar = customCar.copy(
        colourScheme = ColourScheme(Color.MAGENTA)
    )
-----

=== Java (source)
[source,java]
-----
/* Other class definitions ...*/
class Car {
  /* Fields, constructor, getters/setters ...*/
  static class Builder {
    // Defaults
    ColourScheme colourScheme = new ColourScheme(Color.BLACK);
    Propulsion propulsion = new Propulsion("electric");
    Upholstery upholstery = new Upholstery("pvc");

    Builder withColourScheme(ColourScheme colourScheme) {/*...*/}
    Builder withPropulsion(Propulsion propulsion) { /*...*/ }
    Builder withUpholstery(Upholstery upholstery) { /*...*/ }
    Car createCar() { /*...*/ }
  }
}
-----

=== Kotlin (source)
[source,java]
-----
/* Complete */
data class ColourScheme(val colour: Color)
data class Propulsion(val type: String)
data class Upholstery(val fabric: String)

// Default argument values
data class Car(
    val colourScheme: ColourScheme = ColourScheme(Color.BLACK),
    val propulsion: Propulsion = Propulsion("electric"),
    val upholstery: Upholstery = Upholstery("pvc")
)

-----

=== Collections
Java 8 streams finally introduced the filter/map/reduce
API and lambdas but didn't make them available on existing
collections.

=== Java
[source,java]
-----
List<String> colours = new ArrayList() {{
    add("Red"); add("Orange"); add("Yellow"); /**/ add("Violet");
}};

List<String> filtered = colours.stream()
        .filter((c) -> c.toLowerCase().contains("o"))
        .collect(Collectors.toList());

filtered.add("Octarine");

assert filtered.contains("Octarine");
-----

=== Kotlin
[source,java]
-----
// Easy declaration
val colours = listOf("Red", "Orange", "Yellow", /*..*/ "Violet")

// No 'stream' or 'collect'.  Default single argument 'it'
val filtered = colours.filter { it.toLowerCase().contains("o") }
// filtered.add() -- no such method

// Immutable by default
val mutable = filtered.toMutableList()
mutable.add("Octarine")

assert(mutable.contains("Octarine"))
-----

=== 'If' Expressions
* A _statement_ is imperative
** It must have side effects to be useful
* An _expression_ returns a result
** Side-effects are optional

=== Java
[source,java]
-----
boolean proceed = false;

if (lights == RED) proceed = false;
else if (lights == RED && lights == AMBER) proceed = true;
else  proceed = (lights == GREEN);
-----

=== Kotlin
[source,java]
-----
val proceed =
        if (lights == RED) false
        else if (lights == RED && lights == AMBER) true
        else lights == GREEN
-----
or
[source,java]
-----
val size = when (Random().nextInt(100)) {
    in 0.. 10 -> "low"
    in 11..50 -> "medium"
    else -> "high"
}
-----
[NOTE.speaker]
--
Slightly less code, stops assignment and initialisation being accidentally split.
`when` blocks can work with many other built in predicates
--



=== Helper functions

Utility functions that don't belong to a specific class are awkward to
use in Java

* Swap from 'dot' to wrapped function call

=== Java
[source,java]
-----
boolean isPalindrome(String s) {
    return s.equalsIgnoreCase(reverse(s));
}

String reverse(String s) { /*...*/ }

List<String> words = new ArrayList() {{
    add("Anna"); add("Eye"); add("Noon"); add("Civic");
    add("Level");
}};

assert words.stream()
        .allMatch(s -> isPalindrome(s));
-----

=== Kotlin
[source,java]
-----
// Locally-scoped additions to any 'String' instance
fun String.isPalindrome(): Boolean =
        this.equals(this.reverse(), ignoreCase = true)

fun String.reverse(): String { /*...*/ }

val words = listOf("Anna", "Eye", "Noon", "Civic", "Level")

assert(words.all { it.isPalindrome() })
-----


=== Strings
Java `Strings` haven't changed much since the beginning of the language

=== Java
[source,java]
-----

String multiLine = "Windows NT crashed.\n" +
        "I am the Blue Screen of Death.\n" +
        "No one hears your screams.";

String greetingFor(LocalTime now) {
    if (now.isBefore(LocalTime.NOON)) return "Morning";
    else if (now.isBefore(LocalTime.of(18,0))) return "Afternoon";
    else return "Evening";
}

System.out.println("Good " +
        greetingFor(LocalTime.now()) + " Tony.");
-----

=== Kotlin
[source,java]
-----
val multiLine = """The Tao that is seen
Is not the true Tao, until
You bring fresh toner."""

fun LocalTime.greeting(): String = when {
    isBefore(LocalTime.NOON) -> "Morning"
    isBefore(LocalTime.of(18, 0)) -> "Afternoon"
    else -> "Evening"
}

// String interpolation
println("Good ${LocalTime.now().greeting()} Tony.")
-----

=== Delegation
* Reuse through composition

[plantuml]
-----
interface WalkAbility
interface SwimAbility
interface FlyAbility
class WalkMixin implements WalkAbility
class SwimMixin implements SwimAbility
class FlyMixin implements FlyAbility
class Duck {
  walk()
  swim()
  fly()
}
Duck *-- WalkAbility
Duck *-- SwimAbility
Duck *-- FlyAbility

class Penguin {
    walk()
    swim()
}
Penguin *-- WalkAbility
Penguin *-- SwimAbility
-----

=== Java Declaration
[source,java]
-----
interface WalkAbility { void walk(); }
interface FlyAbility { void fly(); }
interface SwimAbility { void swim(); }
class WalkMixin implements WalkAbility {
    public void walk() {}
}
...
class Duck implements WalkAbility, SwimAbility, FlyAbility {
    private WalkAbility w;
    ...
    @Override public void walk() { w.walk(); }
    ...
}
class Penguin implements WalkAbility, SwimAbility {...}
-----

=== Kotlin Declaration
[source,java]
-----
interface WalkAbility { fun walk() }
interface FlyAbility { fun fly() }
interface SwimAbility { fun swim() }
object WalkMixin: WalkAbility {
  override fun walk() {}
}
...

class Duck(w: WalkAbility, f: FlyAbility, s: SwimAbility)
  : WalkAbility by w, FlyAbility by f, SwimAbility by s
class Penguin(w: WalkAbility, s: SwimAbility)
  : WalkAbility by w, SwimAbility by s
-----

=== Java Use
[source,java]
-----
Duck duck = new Duck(
    new WalkMixin(), new SwimMixin(), new FlyMixin());
duck.fly();
duck.swim();
duck.walk();

Penguin penguin = new Penguin(new WalkMixin(), new SwimMixin());
penguin.swim();
penguin.walk();
-----

=== Kotlin Use
[source,java]
-----
val duck = Duck(WalkMixin, FlyMixin, SwimMixin)
duck.fly()
duck.walk()
duck.swim()

val penguin = Penguin(WalkMixin, SwimMixin)
penguin.walk()
penguin.swim()
-----

== Questions?


== End


=== Casting

[source,java]
-----
val x: Any = "bang" // 'Smart' cast
x.toUpperCase() // Compilation error, no method Any#toUpperCase

if (x is String) {
    print(x.toUpperCase()) // x is automatically cast to String
}

val y = x as String // 'Unsafe' cast, may throw exception
y.toUpperCase() // Compiles
-----

[NOTE.speaker]
--
* The compiler tracks any type checks
--
