= Kotlin Introduction
2017-07-19
:revnumber: {project-version}
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../java]

== Outline
* What is Kotlin?
* Where is it used?
* A Better Java
* Things That Java Can't Do

== What is Kotlin
* Statically typed language
* Inspired by Java, Scala, C#, Groovy amongst others
* Targets
** JVM / Android
** JavaScript
** Native


== Short History of Kotlin
* *2010* - Created
* *2016* - 1.0 Release
* *2017* - 1.1 Release, Android 1^st^ class support

== Who Uses Kotlin

== A Better Java

=== Basics
[%step]
* Java / C style
* No semicolons required
* Inferred types
* No ``static`` values
* ``public`` visibility by default
* No checked Exceptions

=== Scripts

(no class/package definition)

[source,java]
-----
import java.io.File

val hosts = File("/etc/hosts").readText()
hosts.split('\n')
        .filter { !it.startsWith('#') }
        .map { it.split("""\s+""")[0] }
        .forEach { println(it) }
-----

[NOTE.speaker]
--
* Compilation overhead
* Useful for experiments
* Can be run from the REPL (``kotlinc``)
--

=== Classes

[source,java]
-----
class TelephoneLine(val number: String) {
    // ...
}
-----

[NOTE.speaker]
--
* A class with a single, immutable property set in the constructor
--

=== Data Classes

[source,java]
-----
data class User(val id: Long, val name: String,
                var lastLogin: Instant = Instant.now())
-----

[NOTE.speaker]
--
* A class with
** three properties (one mutable with a default value)
** ``equals()`` / ``hashCode()``
** ``toString()``
** ``copy()`` (``Clonable`` done right)
--

=== Null Safety

[source,java]
-----
var safe: String = "foo"
safe  = null // Compilation error

val unsafe = null // Compiles

if (unsafe.contains("o")) // Compilation error (may be null)
if (unsafe != null) {
    if (unsafe.contains("o")) { } // OK, checked
}
-----

[NOTE.speaker]
--
* Non-null values enforced *by the compiler*
* The compiler tracks if a nullable value has been checked
--

=== Casting

[source,java]
-----
val x: Any = "bang" // 'Smart' cast
x.toUpperCase() // Compilation error, no method Any#toUpperCase

if (x is String) {
    print(x.toUpperCase()) // x is automatically cast to String
}

val y = x as String // 'Unsafe' cast, may throw exception
y.toUpperCase() // Compiles
-----

[NOTE.speaker]
--
* The compiler tracks any type checks
--

=== Immutability

[source,java]
-----
val immutable = "foo" // Type-inference
immutable = "bar" // Compilation error

val things = listOf("foo", "bar", "baz")
things.remove("baz") // Compilation error
val newThings = things.minus("baz") // 'things' unchanged

val ephemeralThings = mutableListOf("foo", "bar", "baz")
ephemeralThings.remove("baz")
-----

[NOTE.speaker]
--
* Compile-time checks for immutability
--

=== `if` expressions
[source,java]
-----
val proceed =
      if (RED) false
      else if (RED && AMBER && isClear)  true
      else if (GREEN) true
      else false

-----

[NOTE.speaker]
--
* Evaluates to a value
* Must be an exhaustive check
** No need for Ternary expression (``? : ``)
--

=== `when` expressions
[source,java]
-----
val proceed = when {
    RED -> false
    (RED && AMBER && isClear) -> true
    GREEN -> true
    else -> false
}

// Can use any expression
when (x) {
    in 1..10 -> print("x is in the range")
    in validNumbers -> print("x is valid")
    !in 10..20 -> print("x is outside the range")
    else -> print("none of the above")
}
-----

[NOTE.speaker]
--
* Cleaner syntax
* Must be exhaustive when assigning
--

=== `try` expressions

=== Use `elvis` with `return` and `throw`

=== Type Aliases

=== Destructuring
[source,java]
-----
fun printMap(m: Map<String, String>) {
  for (e in m.entries) {
    println("${e.key} -> ${e.value}")
  }
}

// With destructuring
fun printMap(m: Map<String, String>) {
  for ((key, value) in m) {
    println("$key -> $value")
  }
}

-----

=== `apply` for construction
[source,java]
-----
// Construct, populate, return
fun createLabel(): JLabel {
  val label = JLabel("Foo")
  label.foreground = Color.RED
  label.background = Color.BLUE
  return label
}

// using apply
fun createLabel(): JLabel =
  JLabel("Foo").apply {
      foreground = Color.RED
      background = Color.BLUE
  }
-----

== Extensions


== Questions?


== End
